#!/bin/bash

echo "***** Running pre-commit ******"

git stash -q --keep-index

# tengo que correrlo yo (cami) porque no guarda el permiso
chmod +x .git/hooks/pre-commit

echo "* Running ktlintCheck *"
./gradlew ktlintCheck

echo "* Running ktlintFormat *"
./gradlew ktlintFormat

echo "* Running test *"
./gradlew test

echo "* Running jacoco *"
./gradlew jacocoTestReport

echo "***** Done with pre-commit ******"