# This file have the configuration for the CI/CD pipeline

name: Build and Test

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest # construye y prueba un proyecto de gradle en un entorno de ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2 #action para configurar gradle en el entorno de ejecución

      - name: Run tests with Gradle Wrapper
        run: ./gradlew test

      - name: Check code coverage
        run: ./gradlew jacocoTestReport

      - name: Check linting
        run: ./gradlew ktlintCheck

      - name: Check code formatting
        run: ./gradlew ktlintFormat

      - name: Build project with Gradle Wrapper
        run: ./gradlew build
