# This file have the configuration for the CI pipeline

name: Build Project with Gradle ツ

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest # construye y prueba un proyecto de gradle en un entorno de ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2 #action para configurar gradle en el entorno de ejecución

      - name: Format files
        run: ./gradlew ktlintFormat

      - name: Run tests
        run: ./gradlew test

      - name: Build project
        run: ./gradlew build
