name: Publish package to GitHub Packages ツ

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish package
        run: ./gradlew publish
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
